import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { runCapability, outcomeToToolResult } from "../runner.js";
import {
  addressSchema,
  bytes32Schema,
  commonEnvelopeFields,
  uintStringSchema,
} from "../schemas.js";

const CAPABILITY = "invoice";

const inputShape = {
  ...commonEnvelopeFields,
  action: z
    .enum(["issue", "verify", "pay"])
    .describe(
      "'issue' (issuer signs an EIP-712 invoice), 'verify' (recover signer), or 'pay' (verify + settle via pay.once).",
    ),
  payer: addressSchema
    .optional()
    .describe("Required for action=issue. Address expected to pay."),
  token: addressSchema
    .optional()
    .describe("Required for action=issue. ERC-20 contract."),
  amount: uintStringSchema
    .optional()
    .describe("Required for action=issue. Amount due in base units."),
  due_at_unix: z
    .number()
    .int()
    .positive()
    .optional()
    .describe("Required for action=issue. Unix timestamp when invoice is due."),
  memo: z.string().max(256).optional(),
  invoice_id: bytes32Schema
    .optional()
    .describe("Optional. Auto-generated bytes32 if absent."),
  document: z
    .record(z.unknown())
    .optional()
    .describe(
      "Required for action=verify and action=pay. The signed Invoice doc returned by action=issue.",
    ),
};

export function registerInvoice(server: McpServer): void {
  server.registerTool(
    CAPABILITY,
    {
      title: "Lumen: invoice",
      description:
        "Agent-to-agent invoicing via EIP-712 signed documents. action=issue produces a signed Invoice doc; action=verify recovers the signer off-chain; action=pay verifies and settles through pay.once. Documents are portable JSON — exchange via any A2A channel.",
      inputSchema: inputShape,
      annotations: {
        title: "Lumen: invoice",
        destructiveHint: true,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async (args) => {
      const { network, idempotency_key, ...params } = args;
      const outcome = await runCapability(CAPABILITY, {
        ...(network && { network }),
        ...(idempotency_key && { idempotency_key }),
        params,
      });
      return outcomeToToolResult(CAPABILITY, outcome);
    },
  );
}
