import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { runCapability, outcomeToToolResult } from "../runner.js";
import {
  addressSchema,
  bytes32Schema,
  commonEnvelopeFields,
  uintStringSchema,
} from "../schemas.js";

const CAPABILITY = "pay.tip";

const inputShape = {
  ...commonEnvelopeFields,
  action: z
    .enum(["send", "issue", "redeem", "verify"])
    .describe(
      "'send' (default-ish: direct A2A tip with agent metadata), 'issue' (sign a TipClaim ticket without broadcasting), 'redeem' (recipient claims via transferFrom against an existing allowance), 'verify' (off-chain signature check).",
    ),
  recipient: addressSchema
    .optional()
    .describe(
      "Required for action=send and action=issue. Tip destination wallet.",
    ),
  token: addressSchema
    .optional()
    .describe("Required for action=send and action=issue. ERC-20 contract."),
  amount: uintStringSchema
    .optional()
    .describe(
      "Required for action=send and action=issue. Amount in base units (capped at 1e22 by policy).",
    ),
  memo: z.string().max(256).optional(),
  sender_agent_id: z
    .string()
    .max(128)
    .optional()
    .describe(
      "Optional free-form sender identifier captured in the tip receipt.",
    ),
  recipient_agent_id: z
    .string()
    .max(128)
    .optional()
    .describe(
      "Optional free-form recipient identifier captured in the tip receipt.",
    ),
  expiry_unix: z
    .number()
    .int()
    .positive()
    .optional()
    .describe("Required for action=issue. Defaults to 7 days from now."),
  ticket_id: bytes32Schema
    .optional()
    .describe(
      "Optional. Auto-generated bytes32 if absent (action=issue only).",
    ),
  document: z
    .record(z.unknown())
    .optional()
    .describe(
      "Required for action=verify and action=redeem. The signed TipClaim doc returned by action=issue.",
    ),
};

export function registerPayTip(server: McpServer): void {
  server.registerTool(
    CAPABILITY,
    {
      title: "Lumen: pay.tip",
      description:
        "Agent-to-agent micropayments. action=send fires an immediate ERC-20 transfer tagged with sender/recipient agent ids (delegates to pay.once). action=issue produces a signed TipClaim ticket the recipient can redeem later through an existing allowance — action=redeem completes the transferFrom. Policy: tip amounts > 1e22 base units are refused; use pay.once for larger transfers.",
      inputSchema: inputShape,
      annotations: {
        title: "Lumen: pay.tip",
        destructiveHint: true,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    async (args) => {
      const { network, idempotency_key, ...params } = args;
      const outcome = await runCapability(CAPABILITY, {
        ...(network && { network }),
        ...(idempotency_key && { idempotency_key }),
        params,
      });
      return outcomeToToolResult(CAPABILITY, outcome);
    },
  );
}
